baseURL = 'https://spac3.m1n.omg.lol'
languageCode = 'es-es'
title = 'Spac3 by M1n'
theme = "yinyang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "M1n"
  homepage = "https://m1n.omg.lol"

[params]
mainSections = ["posts"]
headTitle = "Spac3 by M1n"
favicon = "/logo.png"
extraHead = '<script defer data-domain="spac3.m1n.omg.lol"></script><script src="https://tinylytics.app/embed/XrQc-jjjMYkBXGckiKzM.js?hits" defer></script>'
postFooterContent = "<br/><a href='https://tinylytics.app/public/g6pNq7Kk-Rg8zw6Mn4As'><p style='text-align: right;'>Visitant3s: <span class='tinylytics_hits'></span><p/></a>"

# extraCSSFiles = ["css/background.css"]

[[params.socials]]
name = "M1n's Profile"
link = "https://m1n.omg.lol"

[[params.socials]]
name = "Proof"
link = "https://proven.lol/da931b"

[[params.socials]]
name = "RSS"
link = "/index.xml"