baseURL = 'https://spac3.m1n.omg.lol'
languageCode = 'es-es'
title = 'Spac3 by M1n'
theme = "yinyang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "M1n"
  homepage = "https://m1n.omg.lol"

[params]
mainSections = ["posts"]
headTitle = "Spac3 by M1n"
favicon = "/logo.png"
# extraCSSFiles = ["css/background.css"]

[[params.socials]]
name = "M1n's Profile"
link = "https://m1n.omg.lol"

[[params.socials]]
name = "RSS"
link = "/index.xml"